on: [push]

name: mabl Simple Example

jobs:
  test:
    name: mabl Test
    environment: Mabl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Functional test deployment in CLI
        uses: mablhq/setup-mabl-cli@v1
        with:
          workspace: lw6LcFr2VZdR0609up8Jcg-w
        env:
          MABL_API_KEY: O6LdVomqVhoeOrchEVveOg

      - name: Run Tests
        run: mabl tests run --id NP8G6QSyhSDdD6ZIwEKK8A-j --headless
